### ISSUE TITLE
Encoding Bug for JsonIo.toJson("🙊🙉🙈", null)?

### ISSUE THREAD

**Issue by raubv0gel** [jdereg/json-io#276]
Is this an encoding bug in `JsonIo.toJson()`?

Using String overloading `JsonIo.toJson()`
![grafik](https://github.com/jdereg/json-io/assets/9824146/9e379411-105d-44b5-9663-06d39af22999)

Using OutputStream overloading `JsonIo.toJson()`
![grafik](https://github.com/jdereg/json-io/assets/9824146/950f31ff-b9b3-4a1d-b273-15bf3357d3ed)

I’m using `com.cedarsoftware:json-io:4.19.9`.

**Comment by jdereg** [comment]
Looking into this.

**Comment by raubv0gel** [comment]
@jdereg, pardon, but do you have any updates on this issue?

**Comment by jdereg** [comment]
Found the issues - there are two of them, one yours, one json-io.  The json-io issue has an easy work around (I'll put a fix anyway).  This particular method advertises that you can pass in null for WriteOptions.  Turns out that is not the case and you get an NPE.  

So add a proper WriteOptions at the end (instead of null for now), like this:
JsonIo.toString(baos, "🙊🙉🙈", new WriteOptionsBuilder().build);

Now, it will still fail for you because toByteArray() on ByteArray does not support the syntax you are using.  You have to convert the ByteArrayOutputStream to a byte[] first, and then create the String from that byte[].

    @Test
    void testUnicodeChars() throws Exception
    {
        String monkeys = "\uD83D\uDE4A\uD83D\uDE49\uD83D\uDE48";
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        JsonIo.toJson(baos, monkeys, new WriteOptionsBuilder().build());
        String json = baos.toString();    // Good
        System.out.println("json = " + json);
        // String json = new String(baos.toByteArray(), StandardCharsets.UTF_8);   // inefficient
        // String json = baos.toString(StandardCharsets.UTF_8);   // invalid
    }

So this will get you going now.  I have a fix coming out for the NPE on null writeOptions.
