### ISSUE TITLE
json-io fails for any immutable map implementation

### ISSUE THREAD

**Issue by Parth-Brahmbhatt** [jdereg/json-io#32]
I was trying to use json-io as part of serializing/deserializing apache storm structures. Storm is written partly in java and partly in clojure. I assumed clojure being JVM compliant json-io should not have any issues serializing/deserializing clojure structures but that is not the case. Following example shows how the deserialization fails for the PersistanceArrayMap structure of clojure which is implemented in java. It seems for the map implementation the code assumes the put method is always supported which is incorrect for any immutable implementation of map. I also tried to serialize Guava's immutable maps and got the same result.

Guava Code Sample:
        ImmutableMap<Object, Object> map = ImmutableMap.builder().put("a", "b").build();
        String s = JsonWriter.objectToJson(map);
        System.out.println(map);
        Object o = JsonReader.jsonToJava(s);
        System.out.println(o);

Exception:
{a=b}
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:326)
	at com.cedarsoftware.util.io.JsonReader.rehashMaps(JsonReader.java:3418)
	at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:1320)
	at com.cedarsoftware.util.io.JsonReader.readObject(JsonReader.java:1278)
	at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:1169)

Clojure Code Sample:
       String s = JsonWriter.objectToJson(clojure.lang.RT.assoc(null, "a", "b"));
       System.out.println(s);
       Object o = JsonReader.jsonToJava(s);
       System.out.println(o);

Exception:
Exception in thread "main" java.lang.UnsupportedOperationException
{"@type":"clojure.lang.PersistentArrayMap","a":"b"}
	at clojure.lang.APersistentMap.put(APersistentMap.java:285)
	at com.cedarsoftware.util.io.JsonReader.rehashMaps(JsonReader.java:3418)
	at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:1320)
	at com.cedarsoftware.util.io.JsonReader.readObject(JsonReader.java:1278)
	at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:1169)

**Comment by jdereg** [comment]
json-io handles Java's Immutable Map and Immutable Collections.  The ImmutableMap you are using is from Google's library, which json-io currently does not link to.

It turns out, you should be be able to handle this with json-io as it ships right now.  Use the JsonReader's assignInstantiator() method.  This allows you to install your own ClassFactory per .class type encountered.  For these Google-specific collections, do the following:

    assignInstantiator(com.google.collection.ImmutableMap.class, YourClassFactory);

When the ImmutableMap.class is encountered, YourClassFactory.newInstance() method will be called.  Return a mutable map so that they reader can write to the Map.  You will need to place the actual class instance name that Google uses as the first argument.  If you want to be more precise, rather than return a regular Map (which would be mutable if you returned...say...LinkedHashMap, you could return a custom Map implementation that is mutable until a 'makeReadyOnly' API (switch) is called.

I could attempt to match classes by "String-Name" in order to choose which Factory class to instantiate, in which case it would allow json-io to mention the Google-specific collections without creating a dependency from json-io to com.google's Immutable classes.  If you have other thoughts or suggestions, I would like to hear them.

**Comment by Parth-Brahmbhatt** [comment]
Thanks.

**Comment by mhmxs** [comment]
Hi @jdereg,

I faced with the same issue with immutable collections, and found your answer. My only problem is for example `com.google.common.collect.RegularImmutableMap` is package private class, so i can't assign it to JsonReader. If i assign the interface of `RegularImmutableMap` `com.google.common.collect.ImmutableMap` json-io shouldn't pick up the registered "instantiator" [here](https://github.com/jdereg/json-io/blob/360402e6ae11cfb7a633b985ffc8850484427ec9/src/main/java/com/cedarsoftware/util/io/JsonReader.java#L723). I'm very new with json-io, but may be should work if:
a) the tool stores string representation of the class name in [factory](https://github.com/jdereg/json-io/blob/360402e6ae11cfb7a633b985ffc8850484427ec9/src/main/java/com/cedarsoftware/util/io/JsonReader.java#L84)
b) iterates on factory elements and uses instanceof to detects "instantiator" instead of plain `factory.get()`

Solution a) is the faster one of course and doesn't break backward compatibility, but i'm interested in your view, or how could i solve the problem in any other way.

Thanks,
Richard
