### ISSUE TITLE
Error deserializing android.net.Uri

### ISSUE THREAD

**Issue by jezzadebate** [jdereg/json-io#34]
Attempting to call .jsonToJava() on a JSON payload which contains an instance of android.net.Uri fails with the following exception:
`
Caused by: java.lang.UnsupportedOperationException
at java.util.AbstractList.add(AbstractList.java:404)
at java.util.AbstractList.add(AbstractList.java:425)
at com.cedarsoftware.util.io.JsonReader.traverseCollection(JsonReader.java:1632)
at com.cedarsoftware.util.io.JsonReader.convertMapsToObjects(JsonReader.java:1372)
at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:1319)
at com.cedarsoftware.util.io.JsonReader.readObject(JsonReader.java:1279)
at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:1170)
`
This is presumably due to the fact that android.net.Uri is an immutable class, and so when deserialization calls for values to be set on the created object this exception is raised. Is this a known bug and if so is there a workaround?

**Comment by jdereg** [comment]
Is there anymore information than what you have sent in terms of the error
stack trace?

**Comment by jezzadebate** [comment]
Here is the JSON payload that is trying to be deserialized. After putting in logging statements, the error occurs when setting the pathSegments (line 1632 of JsonReader.java).


```
{  
   "@type":"android.os.Bundle",
   "mParcelledData":null,
   "mClassLoader":{  
      "@type":"java.lang.BootClassLoader",
      "packages":{  
         "@id":11,
         "@type":"java.util.HashMap",
         "com.android.org.conscrypt":{  
            "@type":"java.lang.Package",
            "implTitle":"Unknown",
            "implVendor":"Unknown",
            "implVersion":"0.0",
            "name":"com.android.org.conscrypt",
            "sealBase":null,
            "specTitle":"Unknown",
            "specVendor":"Unknown",
            "specVersion":"0.0"
         }
      },
      "parent":null
   },
   "mMap":{  
      "android.intent.extra.STREAM":{  
         "@type":"android.net.Uri$StringUri",
         "authority":null,
         "uriString":"content://com.mailreader/5719682/1/contact_save_crash.txt",
         "ssp":null,
         "fragment":null,
         "path":{  
            "pathSegments":[  
               "5719682",
               "1",
               "contact_save_crash.txt"
            ],
            "decoded":"NOT CACHED",
            "encoded":"/5719682/1/contact_save_crash.txt"
         },
         "query":null,
         "scheme":"NOT CACHED",
         "cachedSsi":7,
         "cachedFsi":-2,
         "host":"NOT CACHED",
         "userInfo":null,
         "port":-2
      }
   },
   "mHasFds":false,
   "mFdsKnown":false,
   "mAllowFds":true
}
```

**Comment by jdereg** [comment]
Do you need the mClassLoader field serialized?  If not, I would exclude
that.  I can't imagine that you want to serialize a class loader.  Use the
JsonWriter FIELD_SPECIFIERS option to drop the class loader from the
serialization.  That may be all that you need to do:

*In Groovy:*
JsonWriter.objectToJson(root, [(JsonWriter.FIELD_SPECIFIERS):[(
android.os.Bundle.class):["mParcelledData", "mMap", "mHasFds", "mFdsKnown",
"mAllowFds"]]])

*In Java:*
Map args = new HashMap();
Map fields = new HashMap();
args.put(JsonWriter.FIELD_SPECIFIERS, fields);
Map fieldNames = new ArrayList();
fieldNames.add("mParcelledData");
fieldNames.add("mMap");
fieldNames.add("mHasFds");
fieldNames.add("mFdsKnown");
fieldNames.add("mAllowFds");
fields.put(android.os.Bundle.class,fieldNames);
JsonWriter.objectToJson(root, args);

This tells the JsonWriter that when writing out the
android.os.Bundle.class, only write the following fields listed. I( prefer
Groovy because of the easy-to-read and smaller content to write the
equivalent code.)

Excluding the classLoader field may likely solve your problem.
