### ISSUE TITLE
support jdk 6

### ISSUE THREAD

**Issue by donshop11** [jdereg/json-io#43]
at the moment the library does not work with jdk 6

**Comment by jdereg** [comment]
We are aware of this, as JDK 6 was sunsetting a long time ago, so we have
begun taking advantage of the new Java 7 features.  If you want, since the
full source code is available, you could make the appropriate changes to
support 1.6, and send a pull-request.  If the changes are not too
intrusive, I would consider keeping Java 6 support going forward.

**Comment by jdereg** [comment]
User kkalisz has made the changes necessary to bring json-io back to JDK 1.6 compatibility.  I have incorporated those changes, and will be releasing a new json-io 4.1.0 with JDK 1.6 and higher support.  It will be available in a few hours on Maven Central.

**Comment by jdereg** [comment]
Please note that json-io 4.1.0 now supports JDK 1.6.  Thanks to contributor
kkalisz who made the appropriate changes.
