### ISSUE TITLE
@type not outputed for all data types

### ISSUE THREAD

**Issue by Scitz0** [jdereg/json-io#92]
Even though I added a TYPE arg of true to the writer it did not output @type for all data types. The values in the hashtable for object serialized to disk, int, date and float types has the @type but strings and long does not. 

The writer code:
```
Map<String,Object> params = new HashMap<String,Object>();
params.put(JsonWriter.PRETTY_PRINT, true);
params.put(JsonWriter.TYPE, true);
JsonWriter writer = new JsonWriter(out, params);
writer.write(this);
```

example output:
```
      {
      "@type":"int",
        "value":1
      },
      "Some string value",
      {
        "@type":"date",
        "value":4102441199000
      },
      2234,
```

**Comment by jdereg** [comment]
String and long are 'built-in' data types for JSON and so they are intentionally not marked.  However, an 'int' for example, must be marked as json-io cannot tell if you want the value 100, for example, to be understand as an int or a long.  Similarly, Strings are part of the standard JSON datatypes and need no such additional typing.

**Comment by Scitz0** [comment]
Ok, I just thought this TYPE parameter did just that, output type even if not needed. Makes output more readable when all fields look the same is all.

**Comment by jdereg** [comment]
Your consistent output format point is well-taken.  The TYPE is mainly to ensure all 'object' types are output.  However, it is needed to differentiate the primitive types as well (byte, short, int, long) and float versus double.  Adding the 'TYPE' parameter does make the JSON longer and as a trade-off for space, since the type for long and String can be taken as-is, it was left off.
